agriviTestApp/Models/CompoundsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace agriviTestApp.Models
{
    public class CompoundsViewModel
    {
        public int idSpoja { get; set; }
        public string nazivSpoja { get; set; }
        public int vodik { get; set; }
        public int ugljik { get; set; }
        public int dusik { get; set; }
        public int natrij { get; set; }
        public int kisik { get; set; }
    }
}

agriviTestApp/Models/Spojevi.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace agriviTestApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Spojevi
    {
        public int idSpoja { get; set; }
        [Required(ErrorMessage = "You need to enter a compound name!")]
        public string nazivSpoja { get; set; }
        public int vodik { get; set; }
        public int ugljik { get; set; }
        public int dusik { get; set; }
        public int natrij { get; set; }
        public int kisik { get; set; }

    }
}

agriviTestApp/Models/dataModel.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace agriviTestApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class agriviDBEntities : DbContext
    {
        public agriviDBEntities()
            : base("name=agriviDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Spojevi> Spojevi { get; set; }
    }
}

agriviTestApp/Models/dataModel.Designer.cs
// T4 code generation is enabled for model 'C:\Users\agles\source\repos\agriviTestApp\agriviTestApp\Models\dataModel.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

agriviTestApp/Models/dataModel.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

agriviTestApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using agriviTestApp.Models;

namespace agriviTestApp.Controllers
{
    public class HomeController : Controller
    {
        agriviDBEntities db = new agriviDBEntities();
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetList()
        {
            List<Spojevi> List = db.Spojevi.Select(x => new Spojevi
            {
                idSpoja = x.idSpoja,
                nazivSpoja = x.nazivSpoja,
                vodik = x.vodik,
                ugljik = x.ugljik,
                dusik = x.dusik,
                natrij = x.natrij,
                kisik = x.kisik
            }).ToList();

            return Json(List, JsonRequestBehavior.AllowGet);
        }

    }
}

agriviTestApp/Controllers/compoundsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using agriviTestApp.Models;
using System.Data.Entity;

namespace agriviTestApp.Controllers
{
    public class compoundsController : Controller
    {
        // GET: compounds
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetData()
        {
            using(agriviDBEntities db = new agriviDBEntities())
            {
                List<Spojevi> list = db.Spojevi.ToList<Spojevi>();
                return Json(new { data = list }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]
        public ActionResult AddOrEdit(int id = 0)
        {
            if(id== 0)
            {
                return View(new Spojevi());
            }
            else
            {
                using(agriviDBEntities db = new agriviDBEntities())
                {
                    return View(db.Spojevi.Where(x => x.idSpoja == id).FirstOrDefault<Spojevi>());
                }
            }
        }

        [HttpPost]
        public ActionResult AddOrEdit(Spojevi compound)
        {
            
            using (agriviDBEntities db = new agriviDBEntities())
            {
                if (compound.idSpoja == 0)
                {
                    List<Spojevi> list = db.Spojevi.ToList<Spojevi>();
                    if(list.Count > 0)
                    {
                        compound.idSpoja = list.Last().idSpoja + 1;
                    }
                    db.Spojevi.Add(compound);
                    db.SaveChanges();
                    return Json(new { success = true, message = "Added!", JsonRequestBehavior.AllowGet });
                }
                else
                {
                    db.Entry(compound).State = EntityState.Modified;
                    db.SaveChanges();
                    return Json(new { success = true, message = "Updated!", JsonRequestBehavior.AllowGet });
                }
            }
        }
        [HttpPost]
        public ActionResult Delete(int id)
        {
            using(agriviDBEntities db = new agriviDBEntities())
            {
                Spojevi compound = db.Spojevi.Where(x => x.idSpoja == id).FirstOrDefault<Spojevi>();
                db.Spojevi.Remove(compound);
                db.SaveChanges();
                return Json(new { succes = true, message = "Deleted!", JsonRequestBehavior.AllowGet });
            }
        }
    }
}

agriviTestApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

agriviTestApp/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

agriviTestApp/Views/Home/Index.cshtml
@model agriviTestApp.Models.SpojeviViewModel
@{
    ViewBag.Title = "Index";
}

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />


<div class="container" style="margin-top: 3%;">
    <a href="#" class="btn btn-info" onclick="AddNew(0)">Add new</a><br /><br />
    <table id="tableId" class="table table-striped">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Hydrogen</th>
                <th>Carbon</th>
                <th>Nitrogen</th>
                <th>Sodium</th>
                <th>Oxygen</th>
                <th>Edit</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody id="setList">
            <tr id="status" style="color:red;"></tr>
        </tbody>
    </table>
</div>

<link href="//cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" type="text/css" rel="stylesheet" />
<script src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>


<script>
    $(document).ready(function () {
        $("#tableId").DataTable();
    });

    $("status").html("Loading...");
    $.get("/Home/GetList", null, DataBind);
    function DataBind(ItemList) {
        var setData = $("#setList");
        for (var i = 0; i < ItemList.length; i++) {
            var data = "<tr class='row_" + ItemList[i].idSpoja + "'>" +
                "<td>" + ItemList[i].idSpoja + "</td>" +
                "<td>" + ItemList[i].nazivSpoja + "</td>" +
                "<td>" + ItemList[i].vodik + "</td>" +
                "<td>" + ItemList[i].ugljik + "</td>" +
                "<td>" + ItemList[i].dusik + "</td>" +
                "<td>" + ItemList[i].natrij + "</td>" +
                "<td>" + ItemList[i].kisik + "</td>" +
                "<td>" + "<a href='#' class='btn btn-warning' onclick='Edit(" + ItemList[i].idSpoja + ")'><span class='glyphicon glyphicon-edit'></span></a>" + "</td>" +
                "<td>" + "<a href='#' class='btn btn-danger' onclick='Delete(" + ItemList[i].idSpoja + ")'><span class='glyphicon glyphicon-trash'></span></a>" + "</td>" +
                "</tr>";
            setData.append(data);
            $("#status").html(" ");
        }
    }

</script>

agriviTestApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Agrivi test app by Antonio Glešić</title>
    <link href="~/Content/Site.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />


</head>
<body>
    
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>Chemical compounds - Agrivi test app by Antonio Glešić</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.12.4.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <script src="~/Scripts/notify.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

agriviTestApp/Views/compounds/AddOrEdit.cshtml
@model agriviTestApp.Models.Spojevi
@{
    Layout = null;
}

@using (Html.BeginForm("AddOrEdit", "compounds", FormMethod.Post, new { onsubmit = "return SubmitForm(this)" }))
{
    @Html.HiddenFor(model => model.idSpoja)
    <div class="form-group">
        @Html.TextBoxFor(model => model.nazivSpoja, new { @id = "naziv",@class = "form-control", @placeholder = "Compound name" })
        @Html.ValidationMessageFor(model => model.nazivSpoja)
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.vodik, new { @class = "control-label" })
        @Html.TextBoxFor(model => model.vodik, new { @id = "vodik", @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.ugljik, new { @class = "control-label" })
        @Html.TextBoxFor(model => model.ugljik, new { @id = "ugljik", @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.dusik, new { @class = "control-label" })
        @Html.TextBoxFor(model => model.dusik, new { @id = "dusik", @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.natrij, new { @class = "control-label" })
        @Html.TextBoxFor(model => model.natrij, new { @id = "natrij", @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.kisik, new { @class = "control-label" })
        @Html.TextBoxFor(model => model.kisik, new { @id = "kisik", @class = "form-control" })
    </div>
    <div class="form-group">
        <input id="submit" type="submit" value="Submit" class="btn btn-primary" />
        <input type="reset" value="Reset" class="btn btn-warning" />
    </div>
}


<script>
    $(document).ready(function () {
        $("#submit").prop("disabled", true);
        $(document).keyup(function () {
            var brojac = 0;
            var hydrogen = $("#vodik").val();
            var carbon = $("#ugljik").val();
            var nitrogen = $("#dusik").val();
            var sodium = $("#natrij").val();
            var oxygen = $("#kisik").val();

            if (hydrogen > 0) brojac++;
            if (carbon > 0) brojac++;
            if (nitrogen > 0) brojac++;
            if (sodium > 0) brojac++;
            if (oxygen > 0) brojac++;

            if (brojac >= 2) {
                $("#submit").prop("disabled", false);
            }
        });
    });
    
    

</script>

agriviTestApp/Views/compounds/Index.cshtml
@{
    ViewBag.Title = "Chemical compounds";
}

<a class="btn btn-success" onclick="PopupForm('@Url.Action("AddOrEdit", "compounds")')"><i class="fa fa-plus"></i>  Add new</a><br /><br />

<table id="tableId" class="table table-striped table-bordered" style="width:100%;">
    <thead>
        <tr>
            <th>Compound Name</th>
            <th>Hydrogen</th>
            <th>Carbon</th>
            <th>Nitrogen</th>
            <th>Sodium</th>
            <th>Oxygen</th>
            <th>Edit or Delete</th>
        </tr>
    </thead>
</table>


<link href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />

@section scripts {
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.js"></script>
<script type="text/javascript" charset="utf-8" src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js"></script>


    <script>
        var Popup,DataTable;
        DataTable = $(document).ready(function () {
            $("#tableId").DataTable({
                "ajax": {
                    "url": "/compounds/GetData",
                    "type": "GET",
                    "datatype": "json"
                },
                "columns": [
                    { "data": "nazivSpoja" },
                    { "data": "vodik" },
                    { "data": "ugljik" },
                    { "data": "dusik" },
                    { "data": "natrij" },
                    { "data": "kisik" },
                    {
                        "data": "idSpoja", "render": function (data) {
                            return "<a class='btn btn-default btn-sm' onclick=PopupForm('@Url.Action("AddOrEdit", "compounds")/" + data + "')><i class='fa fa-pencil'></i> Edit </a><a class='btn btn-danger btn-sm' onclick=Delete(" + data + ") style='margin-left:5px'><i class='fa fa-trash'></i> Delete </a>"
                        },
                        "orderable": false,
                        "searchable": false,
                        "width": "150px"
                    }
                ],
                "language": {
                    "emptyTable": "No data available, please click on <b>Add New</b> button"
                },
            });
        });

        function PopupForm(url) {
            var formDiv = $("<div/>");
            $.get(url)
                .done(function (response) {
                    formDiv.html(response);
                    Popup = formDiv.dialog({
                        autoOpen: true,
                        resizable: false,
                        title: 'Enter information',
                        height: 550,
                        width: 600,
                        close: function () {
                            Popup.dialog("destroy").remove();
                            window.location.reload();
                        },

                    });
                });
        }

        function SubmitForm(formData) {

            $.validator.unobtrusive.parse(formData);
            if ($(formData).valid()) {
                $.ajax({
                    type: "POST",
                    url: formData.action,
                    data: $(formData).serialize(),
                    success: function (data) {
                        if (data.success == true) {
                            Popup.dialog("close");
                            DataTable.ajax.reload();

                            $.notify(data.message, {
                                globalPosition: "top center",
                                className: "success"
                            });
                        }
                    }
                });
            }
            return false;
        }

        function Delete(id) {
            if (confirm("Are you sure?")) {
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("Delete", "compounds")/' + id,
                    success: function (data) {
                        if (data.success) {
                            DataTable.ajax.reload();

                            $.notify(data.message, {
                                globalPosition: "top center",
                                className: "success"
                            });
                        }
                    }
                });
            }
            window.location.reload();
        }

    </script>

    }